export const weddingConfig = {
  groom: {
    name: "Dones",
    fullName: "Dones Deska Purwanto",
    parentFather: "Bpk. Nasannudin",
    parentMother: "Ibu Sutrismi",
    photo: "/images/groom.jpg",
    instagram: "@donesdeska",
    childOrder: "Anak ke 2 dari 3 bersaudara",
  },
  bride: {
    name: "Wanda",
    fullName: "Wanda Putri Cantika, S.Pd",
    parentFather: "Bpk. Rohman (Alm.)",
    parentMother: "Ibu Suswati",
    photo: "/images/bride.jpg",
    instagram: "@wandaputri",
    childOrder: "Anak ke 4 dari 5 bersaudara",
  },
  events: [
    {
      id: "akad",
      name: "Akad Nikah",
      date: "2026-07-03",
      time: "15:30 WIB",
      endTime: "Selesai",
      venue: "Kediaman Mempelai Wanita",
      address: "Desa Gandung Baru",
      mapsUrl: "https://maps.app.goo.gl/eBXvqGbfVWzfoLDr9",
    },
    {
      id: "jamuan-kutai",
      name: "Jamuan Kutai",
      date: "2026-07-03",
      time: "19:30 WIB",
      endTime: "Selesai",
      venue: "Kediaman Mempelai Wanita",
      address: "Desa Gandung Baru",
      mapsUrl: "https://maps.app.goo.gl/eBXvqGbfVWzfoLDr9",
    },
    {
      id: "resepsi",
      name: "Resepsi Pernikahan",
      date: "2026-07-04",
      time: "09:00 WIB",
      endTime: "Selesai",
      venue: "Kediaman Mempelai Wanita",
      address: "Desa Gandung Baru",
      mapsUrl: "https://maps.app.goo.gl/eBXvqGbfVWzfoLDr9",
    },
  ],
  weddingDate: "2026-07-03T08:00:00",

  gallery: [
    "/images/gallery/1.jpg",
    "/images/gallery/2.jpg",
    "/images/gallery/3.jpg",
    "/images/gallery/4.jpg",
    "/images/gallery/5.jpg",
    "/images/gallery/6.jpg",
  ],
  gifts: {
    enabled: true,
    bankAccounts: [
      { bank: "BRI", accountNumber: "562301041715534", accountName: "Wanda Putri Cantika" },
    ],
    address: "Desa Gandung Baru",
  },
  music: {
    enabled: true,
    src: "/music/wedding-song.mp3",
    title: "A Thousand Years",
    artist: "Christina Perri",
  },
  hashtag: "#DonesWanda2026",
  quote: "Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu dari jenismu sendiri, agar kamu cenderung dan merasa tenteram kepadanya. (QS. Ar-Rum: 21)",
}
